name: ${PROJECT_NAME}

services:
    discord-bot:
        build: .
        container_name: ${BOT_CONTAINER_NAME}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ../.env:/app/.env
