name: ${PROJECT_NAME}

services:
    minecraft:
        image: itzg/minecraft-server:latest
        container_name: ${MINECRAFT_CONTAINER_NAME}
        tty: true
        stdin_open: true
        ports:
            - "${MINECRAFT_PORT}:25565"
            - "${SSH_PORT}:2222" 
        environment:
            EULA: "TRUE"
            TYPE: "NEOFORGE"
            VERSION: "1.21.1"
            NEOFORGE_VERSION: "21.1.235"
            MEMORY: ${MEMORY}
            ENABLE_SSH: "true"
            RCON_PASSWORD: ${SSH_PASSWORD}
            ONLINE_MODE: "FALSE"
        volumes:
            - ${MODS_DIR}:/data/mods
            # - ${WORLD_VOLUME}
